### ISSUE TITLE
Is there a way to listen for exception events?

### ISSUE THREAD

**Issue by CMCDragonkai** [stackphp/builder#7]
The normal HTTPKernel allowed you to listen to exception events.

How do you do it with StackPHP Builder?

**Comment by simensen** [comment]
I'm going to close this because the work put into making truly "framework agnostic HTTP code for PHP" is based around PSR-7 and related PSR's currently working through PHP-FIG. I suspect that StackPHP is going to continue to be Syfmony-ecosystem-only for the foreseeable future and I think that is fine. This issue is very old so I'm guessing it won't be a problem to close but feel free to chime in again if this is still an issue or open another one with any ideas that have changed since it was originally opened.
